name: open_ai_chat_bot
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  speech_to_text: ^6.3.0
  http: ^1.1.0
  flutter_tts: ^3.7.0
  animate_do: ^3.0.2

  hexcolor: ^3.0.1
  proste_bezier_curve: ^2.0.2
  flutter_svg: ^2.0.10+1


  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  drift: ^2.9.0
  sqlite3_flutter_libs: ^0.5.20
  path_provider: ^2.0.0
  path: ^1.8.3
  sqlite3: ^2.1.0
  webview_flutter: ^4.5.0
  url_launcher: ^6.1.14
  desktop_webview_window: ^0.2.3
  webview_windows: ^0.4.0
  dart_openai: ^5.1.0

  flutter_screenutil: 5.9.3
  json_serializable: ^6.8.0
  json_annotation: ^4.9.0
  intl: ^0.19.0
  shamsi_date: ^1.0.2
  provider: ^6.1.2
  awesome_notifications_core: ^0.9.0
  awesome_notifications: 0.8.3
  lazy_load_scrollview: ^1.3.0



dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^7.1.1
  drift_dev: ^2.9.0
  build_runner: ^2.4.9
  change_app_package_name: ^1.2.0

  stylish_bottom_bar: ^1.1.0
  flutter_lints: ^2.0.0
  draggable_bottom_sheet: ^1.0.2
  graphql_flutter: ^5.1.2


flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/sounds/
    - assets/icons/


  fonts:
    - family: Cera Pro
      fonts:
        - asset: assets/fonts/Cera-Pro-Bold.otf
        - asset: assets/fonts/Cera-Pro-Medium.otf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
